version: "3.9"
name: oop-appstore


services:
    postgres:
        image: "${DB_IMAGE}:${DB_VERSION}"
        container_name: "${DB_IMAGE}-${DB_VERSION}"
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_ADMIN}
            POSTGRES_PASSWORD: ${DB_ADMIN_PASS}
        ports:
            - "${DB_PORT_FROM}:${DB_PORT_TO}"
        volumes:
            - ${DB_VOLUME}


volumes:
    OOP-AppStore:
